# Generated by Django 3.0 on 2020-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='twiter',
            new_name='twitter',
        ),
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
    ]
