# Generated by Django 3.0 on 2020-01-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Plato')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='menus', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creaciòn')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Ediciòn')),
            ],
        ),
    ]
