# Generated by Django 3.0 on 2020-01-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200126_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=2, verbose_name='Precio'),
        ),
    ]
